// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxmtihysjjjlbrdxcbyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4bXRpaHlzampqbGJyZHhjYnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mjg3NjIsImV4cCI6MjA2MDIwNDc2Mn0.9iNkaFwl5la-roPBUHT4afZdiaTyt7tcIFt4oIAyljo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);